export { default as Step1_BasicUserInfo } from "./Step1_BasicUserInfo";
export { default as Step2_EmailVerification } from "./Step2_EmailVerification";
export { default as Step3_PharmacyInfo } from "./Step3_PharmacyInfo";
export { default as Step4_AddressLocation } from "./Step4_AddressLocation";
export { default as Step5_Documents } from "./Step5_Documents";
export { default as Step6_Images } from "./Step6_Images";
export { default as Step7_PaymentDelivery } from "./Step7_PaymentDelivery";
export { default as Step8_Review } from "./Step8_Review";
export { default as Step9_Success } from "./Step9_Success";
